---
# defaults file for os
kvm_packages:
  - "@virt"
  - "virt-top"
  - "libguestfs-tools"
  - "virt-install"
  - "virt-viewer"
  # ansible virt need lxml
  - python3-lxml
  - python3-pip
  # Important for python3-openshift
  - python3-requests-oauthlib
  # Need's epel - is enabled by default on hetzner
  - python3-openshift
  # It looks like firewalld is not installed in CentOS Stream
  - firewalld

cockpit_packages:
  - cockpit 
  - cockpit-machines
  - cockpit-podman
  # podman is not a cockpit package but I am too lazy to create a new variable
  - podman