---
# defaults file for os
kvm_packages:
  - "@virtualization-hypervisor"
  - "@virtualization-client"
  - "@virtualization-platform"
  - "@virtualization-tools"
  # ansible virt need lxml
  - python3-lxml
  - python3-pip
  # Important for python3-openshift
  - python3-requests-oauthlib
  # Need's epel - is enabled by default on hetzner
  - python3-openshift
  # It looks like firewalld is not installed in CentOS Stream
  - firewalld
