---

- name: Collect services facts
  service_facts:
  register: services_state
  become: true

- name: Stop and disable {{ lb_name }}.service
  systemd:
    name: "{{ lb_name }}.service"
    enabled: false
    state: stopped
  when: services_state.ansible_facts.services[ lb_name  + '.service'] is defined
  become: true

- name: Remove OpenShift 4 Loadbalancer SystemD service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/sysconfig/{{ lb_name }}.env"
    - "/etc/systemd/system/{{ lb_name }}.service"
  become: true

- name: Podman will stay in the Host, Play with it! ;-)
  debug:
    msg: "Podman will stay in the Host, Play with it! ;-)"
