---
# defaults file for okd-facts

vn_subnet: "192.168.50.0"
vn_name: "vmnet01"
vn_internal_domain: "compute.local"
vn_public_domain: "ulozaka.com"
public_domain: "ulozaka.com"

#
ip_families:
  - IPv4

# VM flavors
master_count: 3
master_vcpu: 4
master_memory_size: 16384
master_memory_unit: 'MiB'
# qemu-img image size specified.
#   You may use k, M, G, T, P or E suffixe
master_root_disk_size: '120G'

compute_count: 3
compute_vcpu: 2
compute_memory_size: 8192
compute_memory_unit: 'MiB'
# qemu-img image size specified.
#   You may use k, M, G, T, P or E suffixe
compute_root_disk_size: '120G'
