---
- name: Destroy VM {{ vm_instance_name }}
  virt:
    command: destroy
    name: "{{ vm_instance_name }}"
  ignore_errors: yes
  become: true

- name: Undefine VM {{ vm_instance_name }}
  virt:
    command: undefine
    name: "{{ vm_instance_name }}"
  ignore_errors: yes
  become: true

- name: Delete disk {{ vm_instance_name }}
  file:
    path: "{{ vms_base_path }}/images/{{ vm_instance_name }}.qcow2"
    state: absent
  when: vm_storage_backend == "qcow2"
  become: true

- name: Delete ignition {{ vm_instance_name }}
  file:
    path: "{{ vms_base_path }}/images/{{ vm_instance_name }}.ign"
    state: absent
  become: true