---
- name: Create certificates dir
  file:
    path: "{{ le_certificates_dir }}/{{ le_public_domain }}"
    state: directory
    mode: 0755

- name: Create account-key
  openssl_privatekey:
    path: "{{ le_certificates_dir }}/account.key"
    type: RSA
    size: 4096

- name: Fetch letsencrypt root ca
  get_url:
    url: https://letsencrypt.org/certs/isrgrootx1.pem.txt
    dest: "{{ le_certificates_dir }}/isrgrootx1.pem"

- name: Create {{ le_public_domain }}.key
  openssl_privatekey:
    path: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.key"
    type: RSA
    size: 4096

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  openssl_csr:
    path: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.csr"
    privatekey_path: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.key"
    subject_alt_name: "DNS:*.apps.{{ le_public_domain }},DNS:api.{{ le_public_domain }}"

- name: Create a challenge for {{ le_public_domain }} using a account key file.
  acme_certificate:
    account_key_src: "{{ le_certificates_dir }}/account.key"
    account_email: "{{ le_letsencrypt_account_email }}"
    src: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.csr"
    cert: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.crt"
    challenge: dns-01
    acme_directory: "{{ le_acme_directory }}"
    acme_version: 2
    # Renew if the certificate is at least 30 days old
    remaining_days: 60
    terms_agreed: yes
  register: sample_com_challenge

- name: Debug var only with -vv
  debug:
    var: sample_com_challenge
    verbosity: 2

- name: Set challenge_data_dns
  set_fact:  # noqa no-handler
    challenge_data_dns: "{{ sample_com_challenge.challenge_data_dns }}"
  when: sample_com_challenge is changed

- name: Create DNS record at CloudFlare
  cloudflare_dns:
    zone: "{{ le_cloudflare_zone }}"
    record: "{{ item.0.key }}"
    # 1 for automatic
    ttl: 1
    type: TXT
    value: "{{ item.1 }}"
    api_token: "{{ cloudflare_account_api_token }}"
  register: record
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: le_dns_provider == "cloudflare" and sample_com_challenge is changed

- name: DNS record info
  debug:    # noqa no-handler
    msg: "{{ item.0.key }} TXT {{ item.1 }}"
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: sample_com_challenge is changed

- name: Pause, wait for DNS changes
  pause:   # noqa no-handler
    seconds: 120
  when: sample_com_challenge is changed

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  acme_certificate:  # noqa no-handler
    account_key_src: "{{ le_certificates_dir }}/account.key"
    account_email: "{{ le_letsencrypt_account_email }}"
    src: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.csr"
    cert: "{{ le_certificates_dir }}/{{ le_public_domain }}/cert.crt"
    fullchain: "{{ le_certificates_dir }}/{{ le_public_domain }}/fullchain.crt"
    chain: "{{ le_certificates_dir }}/{{ le_public_domain }}/intermediate.crt"
    challenge: dns-01
    acme_version: 2
    acme_directory: "{{ le_acme_directory }}"
    remaining_days: 60
    data: "{{ sample_com_challenge }}"
  when: sample_com_challenge is changed

- name: Delete DNS record at CloudFlare
  cloudflare_dns:
    zone: "{{ le_cloudflare_zone }}"
    record: "{{ item.0.key }}"
    # 1 for automatic
    ttl: 1
    type: TXT
    value: "{{ item.1 }}"
    api_token: "{{ cloudflare_account_api_token }}"
    state: absent
  loop: "{{ challenge_data_dns | default({}) | dict2items | subelements('value') }}"
  when: le_dns_provider == "cloudflare" and sample_com_challenge is changed

- name: concat root ca and intermediate
  shell: "cat {{ le_certificates_dir }}/isrgrootx1.pem {{ le_certificates_dir }}/{{ le_public_domain }}/intermediate.crt >> {{ le_certificates_dir }}/{{ le_public_domain }}/ca-bundle.pem"   # noqa line-length
  args:
    creates: "{{ le_certificates_dir }}/{{ le_public_domain }}/ca-bundle.pem"