---
- name: Include DNS provider
  include: "create-{{ pd_provider }}.yml"

- name: Add api.{{ cluster_name }}.{{ pd_public_domain }} to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cluster_name }}.{{ pd_public_domain }}"
    block: |
      "{{ pd_public_ip }} api.{{ cluster_name }}.{{ pd_public_domain }}"
  tags: public_dns
  become: true

- name: Include DNS provider
  include: "letsencrypt.yml"
  when: letsencrypt_disabled == false

