---
# Debug...
# - template:
#     src: templates/network.xml.j2
#     dest: network.xml


#
# Libvirt Network
#

- name: Define network {{ cluster_name }}
  virt_net:
    command: define
    name: "{{ cluster_name }}"
    xml: "{{ lookup('template', 'templates/network.xml.j2') }}"

- name: Active network {{ cluster_name }}
  virt_net:
    state: active
    name: "{{ cluster_name }}"

- name: Activate autostart network {{ cluster_name }}
  virt_net:
    autostart: yes
    name: "{{ cluster_name }}"

#
#  Load Balancer
#
- name: Build haproxy config
  set_fact:
    lb_haproxy_cfg: "{{ lookup('template','templates/haproxy.conf.j2') }}"

- name: Debug haproxy config
  debug:
    msg: "{{ lb_haproxy_cfg.split('\n') }}"
    verbosity: 1

# - name: Create OpenShift 4 load balancer
#   import_role:
#     name: openshift-4-loadbalancer
#     tasks_from: create.yml
#   vars:
#     lb_name: "openshift-4-loadbalancer-{{ cluster_name }}"
#     lb_haproxy_cfg: "{{ lb_haproxy_cfg }}"
#   tags: lb

#
# Public DNS
#
# - name: Create public dns entries
#   import_role:
#     name: public_dns
#     tasks_from: create.yml
#   vars:
#     pd_provider: "{{ dns_provider }}"
#     pd_public_ip: "{% if 'IPv4' in ip_families %}{{ public_ip | default(listen_address) }}{% endif %}"
#     pd_public_ipv6: "{% if 'IPv6' in ip_families %}{{ public_ipv6 | default(listen_address_ipv6) }}{% endif %}"
#     pd_cloudflare_account_api_token: "{{ cloudflare_account_api_token }}"
#     pd_cloudflare_zone: "{{ cloudflare_zone }}"
#     pd_aws_access_key: "{{ aws_access_key }}"
#     pd_aws_secret_key: "{{ aws_secret_key }}"
#     pd_aws_zone: "{{ aws_zone }}"
#     pd_hetzner_account_api_token: "{{ hetzner_account_api_token }}"
#     pd_hetzner_zone: "{{ hetzner_zone }}"
#     pd_public_domain: "{{ cluster_name }}.{{ public_domain }}"
#   tags: public_dns
#   when: dns_provider != 'none'

- name: Add api.{{ cluster_name }}.{{ public_domain }} to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cluster_name }}.{{ public_domain }}"
    block: |
      {{ listen_address }} api.{{ cluster_name }}.{{ public_domain }}
  tags: public_dns
  become: true
