---
# Debug...
# - template:
#     src: templates/network.xml.j2
#     dest: network.xml


#
# Libvirt Network
#

- name: Define network {{ cluster_name }}
  virt_net:
    command: define
    name: "{{ cluster_name }}"
    xml: "{{ lookup('template', 'templates/network.xml.j2') }}"

- name: Active network {{ cluster_name }}
  virt_net:
    state: active
    name: "{{ cluster_name }}"

- name: Activate autostart network {{ cluster_name }}
  virt_net:
    autostart: yes
    name: "{{ cluster_name }}"

