#!/usr/bin/env ansible-playbook
---
- hosts: infra
  tasks:
    - name: Set OpenShift cluster facts
      import_role:
        name: okd-facts
    - name: Prepare infra host
      import_role:
        name: os
      tags: os
    - name: Setup public DNS entries
      import_role:
        name: dns
      when: dns_provider != 'none'
      tags:
        - public_dns
        - certificates
    # @TODO
    # Check in which role we need to gather facts
    # and disable fact gathering for more performance
    #      gather_facts: false
    - name: Configure KVM
      import_role:
        name: kvm
    - name: Create OKD 4 load balancer
      import_role:
        name: loadbalancer
      tags: lb
    - name: Prepare OKD4
      import_role:
        name: prepare-okd
