#!/usr/bin/env ansible-playbook
---
- hosts: infra
  tasks:
    - name: Prepare infra host
      import_role:
        name: os
      tags: os 
    - name: Configure KVM
      import_role:
        name: kvm


