#!/usr/bin/env ansible-playbook
---
- hosts: infra
  tasks:
    - name: Set OpenShift cluster facts
      import_role:
        name: okd-facts
# @TODO
# Check in which role we need to gather facts
# and disable fact gathering for more performance
#      gather_facts: false
    - name: Prepare infra host
      import_role:
        name: os
      tags: os 
    - name: Configure KVM
      import_role:
        name: kvm




