---
# certificates_dir: "{{ playbook_dir }}/../certificate"
# certficate_fullchain: "{{ certificates_dir }}/{{ cluster_name }}.{{ public_domain }}/fullchain.crt"
# certficate_key: "{{ certificates_dir }}/{{ cluster_name }}.{{ public_domain }}/cert.key"
# Default production directory
# Production directory: https://acme-v02.api.letsencrypt.org/directory
# Staging directory: "https://acme-staging-v02.api.letsencrypt.org/directory"
letsencrypt_directory: "https://acme-v02.api.letsencrypt.org/directory"
# By default letsencrypt is enabled.
letsencrypt_disabled: false
# helm
helm_cli_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/helm/latest/helm-linux-amd64"

butane_cli_location: "{{ openshift_mirror }}/pub/openshift-v4/clients/butane/latest/butane-amd64"


# NFS Storage
#  storage_nfs do not support multi cluster support, it overwrites the
#  /etc/exports
storage_nfs: false
storage_nfs_path_prefix: '/var/lib/libvirt/images'
storage_nfs_target_namespace: openshift-nfs-provisioner
